spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: myuser
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  data:
    redis:
      host: redis
      port: 6379